CONFIG:
  你的邮箱:
    你的cloudflare api:
      你要修改的域名ID1:
        你要修改的域名解析记录ID1:
           CM:地区
        你要修改的域名解析记录ID2:
           CU:HKG
        你要修改的域名解析记录ID3:
           CT:all
      你要修改的域名ID2: 
        格式如上

MODE: 3